### ISSUE TITLE
`Reset Mirrors to Defaults` is out of date (resets to Ubuntu instead of apt.pop-os.org)

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/repoman#100]
Following https://github.com/pop-os/default-settings/pull/141, the default apt source should be `apt.pop-os.org/ubuntu` instead of `us.archive.ubuntu.com/ubuntu`. The `Reset Mirrors to Default` button currently still resets to the old default.

**Comment by n3m0-22** [comment]
@jacobgkau I was checking out `repoman` and it looks like it gets the wrong address from `/etc/apt/sources.list.d/system.sources`. If I change the last line in that file from `X-Repolib-Default-Mirror: http://us.archive.ubuntu.com/ubuntu` to `X-Repolib-Default-Mirror: http://apt.pop-os.org/ubuntu/` it fixes `Reset Mirrors to Defaults`. I'm not sure but I think this [line](https://github.com/pop-os/system-updater/blob/500a384cf687e5e14aba8e01caec0157dc63a167/daemon/src/package_managers/apt_pop.rs#L33) from [system-updater](https://github.com/pop-os/system-updater) might be the cause. I've tried making the change and building `system-updater` locally with no luck, but I could be doing something wrong, or just be looking in the wrong place. Either way, maybe this will help to diagnose the root cause.
